version: 2
jobs:
  test:
    docker:
      - image: "circleci/node:10"
    environment:
      NODE_CONFIG_DIR: "/tmp"
    working_directory: ~/nd-js
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'node-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}'
            - 'node-v1-{{ checksum "package.json" }}'
            - node-v1-
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            test -f "cc-test-reporter" || curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          paths:
            - node_modules
            - cc-test-reporter
          key: 'node-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}'
      - run:
          name: Compile the code
          command: yarn compile --verbose
      - run:
          name: Program information
          command: |
            yarn start information
            yarn start:admin information
      - run:
          name: Testing
          command: |
            ./cc-test-reporter before-build
            yarn coverage:ci
            ./cc-test-reporter after-build --exit-code $?
      - run:
          name: Update CodeCov.io
          command: |
            curl -s https://codecov.io/bash | bash
      - store_test_results:
          path: coverage/reporter
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: .caches
          destination: caches
      - store_artifacts:
          path: .caches/webpack
          destination: webpack
  build:
    docker:
      - image: "circleci/node:10"
    environment:
      NODE_CONFIG_DIR: "/tmp"
    working_directory: ~/nd-js
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: "Build resource and command via PKG"
          command: ./scripts/deployment.js all --ci
      - store_artifacts:
          path: .caches
          destination: caches
      - store_artifacts:
          path: bin
          destination: deployments
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - master
          requires:
            - test
