style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/nd-js
options:
  commits:
    filters:
      Type:
        - feature
        - improve
        - fix
        - doc
  commit_groups:
    title_maps:
      feature: Features
      improve: Improving User Experience
      fix: Fixes Bug
      doc: Documentation
  header:
    pattern: "^\\[(\\w*)\\]\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
